# build stage
FROM node:18 as build
WORKDIR /app
COPY accesibilidad-demo/package.json ./
COPY accesibilidad-demo/package-lock.json ./
RUN npm install --force
COPY accesibilidad-demo .
RUN npm run build

# production stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
